### ISSUE TITLE
MATLAB app crashes on (first) Initialization 

### ISSUE THREAD

**Issue by eioe** [chriscline/VRDigitizer#1] opened 2019-11-05 14:42 UTC
VRDigitizer MATLAB app crashes when running it for the first time. 
I installed it as described in the README. It also shows up in MATLAB's App section. When starting it from there, during initialization of the GUI, it crashes with error code:

    Undefined function 'setVerticalAlignment' for input arguments of type 'handle.handle'.

    Error in c_GUI_ColorIndicator (line 71)
	    				    jh.setVerticalAlignment(javax.swing.JLabel.CENTER)

[see below for full traceback.)

Setup: 
MATLAB R2018b
Windows10
SteamVR 1.8.5 + HTC Vive Pro

**Full output + _traceback_:**
15:31:52 v Initializing VRDigitizerGUI
15:31:53 |v Closing VRDigitizerGUI
15:31:53 | > Killing VRDigitizer_helper.exe
15:31:53 | > Saving persistent settings to C:\Users\Felix\AppData\Roaming\MathWorks\MATLAB Add-Ons\Apps\VRDigitizer - 2\VRDigitizerGUI_SavedSettings.mat
15:31:53 |^ 
15:31:53 |v Loading saved settings from C:\Users\Felix\AppData\Roaming\MathWorks\MATLAB Add-Ons\Apps\VRDigitizer - 2\VRDigitizerGUI_SavedSettings.mat
15:31:53 | > Saved setting for windowPosition overriding default
15:31:53 | > Saved setting for speechLexiconPath overriding default
15:31:53 | > Saved setting for templateMontagePath overriding default
15:31:53 | > Saved setting for helperExePath overriding default
15:31:53 | > Saved setting for meshPath overriding default
15:31:53 | > Saved setting for controllerMeshPath overriding default
15:31:53 | > Saved setting for trackerMeshPath overriding default
15:31:53 | > Saved setting for hmdMeshPath overriding default
15:31:53 |^ 
15:31:53 |> Launching C:\Users\Felix\AppData\Roaming\MathWorks\MATLAB Add-Ons\Apps\VRDigitizer - 2\python\build\exe.win32-2.7\VRDigitizer_helper.exe

Undefined function 'setVerticalAlignment' for input arguments of type 'handle.handle'.

Error in c_GUI_ColorIndicator (line 71)
					jh.setVerticalAlignment(javax.swing.JLabel.CENTER)

Error in VRDigitizerGUI/initializeControls_main (line 533)
			guiH.(['vrStatus_' s.trackedDevices{iD}]) = c_GUI_ColorIndicator(...

Error in VRDigitizerGUI (line 285)
	initializeControls_main();

Error in VRDigitizer0x2D2App/startApp (line 84)
                eval('VRDigitizerGUI');

Error in VRDigitizer0x2D2App (line 48)
            startApp(obj)

Error in appinstall.internal.runapp>execute (line 116)
out = evalin('caller', [script ';']);

Error in appinstall.internal.runapp>runapp13a (line 95)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));

Error in appinstall.internal.runapp>preamble18b (line 60)
    appobj = runapp13a(appinstalldir);

Error in appinstall.internal.runapp (line 13)
    out = preamble18b(appinstalldir);

Error in matlab.apputil.run (line 45)
appinstall.internal.runapp(appName, appLocation);

**Comment by chriscline** [comment] 2019-11-10 02:33
I could reproduce this issue with R2018b as well. Turns out it's a compatibility issue with `findjobj`. Fixed by updating to newer [`findjobj`](https://www.mathworks.com/matlabcentral/fileexchange/14317-findjobj-find-java-handles-of-matlab-graphic-objects) in 393845702a0cb435066132866c47d8c279cf4614.

**Closed as completed by chriscline** 2019-11-10 02:33 UTC
